# Generated by Django 5.1.2 on 2024-10-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='finca',
            name='capacidad_animales',
        ),
        migrations.RemoveField(
            model_name='finca',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='ternero',
            name='finca',
        ),
        migrations.RemoveField(
            model_name='vaca',
            name='finca',
        ),
        migrations.AddField(
            model_name='finca',
            name='asnm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finca',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finca',
            name='ciudad',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='finca',
            name='hectareas',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='finca',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='ternero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaca',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
