# Generated by Django 5.1.2 on 2024-10-31 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0002_remove_finca_altura_remove_finca_capacidad_animales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccionleche',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PesoVaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to='ganaderia.vaca')),
            ],
        ),
        migrations.DeleteModel(
            name='Peso',
        ),
    ]
