# Generated by Django 5.1.2 on 2024-10-31 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0003_alter_produccionleche_fecha_pesovaca_delete_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesovaca',
            name='vaca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.vaca'),
        ),
    ]
