# Generated by Django 5.1.2 on 2024-10-31 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0004_alter_pesovaca_vaca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesoternero',
            old_name='fecha',
            new_name='fecha_peso',
        ),
        migrations.AlterField(
            model_name='pesoternero',
            name='ternero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.ternero'),
        ),
    ]
