# Generated by Django 5.1.2 on 2024-10-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0005_rename_fecha_pesoternero_fecha_peso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesoternero',
            old_name='fecha_peso',
            new_name='fecha',
        ),
    ]
