# Generated by Django 5.1.2 on 2024-10-31 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0006_rename_fecha_peso_pesoternero_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('en_produccion', models.BooleanField(default=False)),
                ('genero', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=6)),
                ('en_crecimiento', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Leche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.animal')),
            ],
        ),
    ]
