# Generated by Django 5.1.2 on 2024-11-07 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0009_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ganaderia.ciudad'),
        ),
    ]
