# Generated by Django 5.1.2 on 2024-11-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0010_alter_finca_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': False},
        ),
    ]
