# Generated by Django 5.1.2 on 2024-11-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0011_alter_ciudad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='asnm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='finca',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finca',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.ciudad'),
        ),
        migrations.AlterField(
            model_name='finca',
            name='hectareas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finca',
            name='temperatura',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='ciudad',
            table='ganaderia_ciudad',
        ),
    ]
