# Generated by Django 5.1.2 on 2024-11-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0012_alter_finca_asnm_alter_finca_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='finca',
            name='asnm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finca',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finca',
            name='hectareas',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='finca',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
    ]
