# Generated by Django 5.1.2 on 2024-11-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0013_alter_finca_ciudad_alter_finca_asnm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaca',
            name='es_productiva',
            field=models.BooleanField(default=True),
        ),
    ]
