# Generated by Django 5.1.2 on 2024-11-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0014_vaca_es_productiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='vaca',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='ganaderia.vaca'),
        ),
    ]
