# Generated by Django 5.1.2 on 2024-11-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0015_animal_vaca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ternero',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=6),
        ),
    ]
