# Generated by Django 5.1.2 on 2024-11-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0016_alter_ternero_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ternero',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=6),
        ),
    ]
