# Generated by Django 5.1.2 on 2024-11-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0017_alter_ternero_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaca',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vacas/fotos/'),
        ),
    ]
