# Generated by Django 5.1.2 on 2024-11-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0018_vaca_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaca',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vacas_fotos/'),
        ),
    ]
