# Generated by Django 5.1.2 on 2024-11-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0019_alter_vaca_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaca',
            name='foto',
        ),
    ]
